export const robots = [
  {
    id: 1,
    name: "Lean Graham",
    username: "Bret",
    email: "Sincere@april.biz",
  },
  {
    id: 2,
    name: "Ervin Howell",
    username: "Antonette",
    email: "Shanna@melissa.tv",
  },
  {
    id: 3,
    name: "Clementine Bauch",
    username: "Samantha",
    email: "Nathan@yesenia.net",
  },
  {
    id: 4,
    name: "Nathan Prescot",
    username: "Nestaniel",
    email: "Nat.bronco@westin.io",
  },
  {
    id: 5,
    name: "Brig Jake",
    username: "brigam",
    email: "brigam@young.net",
  },
  {
    id: 6,
    name: "Mick Lovin",
    username: "Mattiyahu",
    email: "beezwax@jastion.xyz",
  },
  {
    id: 7,
    name: "Felicia Towers",
    username: "byfelicia",
    email: "donston@towers.net",
  },
  {
    id: 8,
    name: "Master Blue",
    username: "big bad tide",
    email: "wedian@masters.net",
  },
  {
    id: 9,
    name: "TJ sneakers",
    username: "Lil TJ",
    email: "sugargoo@towers.net",
  },
  {
    id: 10,
    name: "Mark Abram",
    username: "Ngonyi",
    email: "cheetah@april.iz",
  },
  {
    id: 11,
    name: "Ogona Festus",
    username: "Scam Likely",
    email: "Shakea@jalenda.tv",
  },
  {
    id: 12,
    name: "Von Brunc",
    username: "Hamilton",
    email: "Nat.turner@rebellion.rn",
  },
  {
    id: 13,
    name: "scotty Prescot",
    username: "Neelington",
    email: "Nat.dwift@westin.io",
  },
  {
    id: 14,
    name: "swifton Jake",
    username: "YoungBoy",
    email: "Jaen@rebat.net",
  },
  {
    id: 15,
    name: "Carston Blank",
    username: "bummyjame",
    email: "claris@jastion.xyz",
  },
];
